version: "3.0"

services:
  postgres:
    ports:
      # HOST:CONTAINER
      - "5433:5432"
    container_name: postgres-dashboard
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: revamp
    volumes:
      - ${HOME}/logs/postgres-dashboard:/var/lib/postgresql/data
    networks:
      default: 
        ipv4_address: 172.18.0.100

networks:
  default:
    external:
      name: o4s_rivendell

volumes:
  postgres-dashboard: