version: "3"
services:
  mongodb:
    container_name: mongo-dashboard
    image: mongo:4.0.4
    volumes:
      - ${HOME}/logs/mongo-dashboard:/data/db
      - ${HOME}/logs/configdb:/data/configdb
      - ${HOME}/logs/o4s:/data/o4s
    ports:
      - "27017:27017"
    networks:
      - default

networks:
  default:
    external:
      name: o4s_rivendell