version: "3.0"

services:
  mysql:
    image: mysql:5.6
    container_name: mysql-local
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: 'local'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ${HOME}/logs/mysql:/var/lib/mysql
    networks:
      - 'default' 

networks:
  default:
    external:
      name: o4s_rivendell

volumes:
  mysql: